version: '3'
services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgis-data:/var/lib/postgresql/data
    env_file: docker/.env
  app:
    build:
      context: .
      dockerfile: docker/dockerfile
    volumes:
      - .:/home/dockeruser/app
    env_file: docker/.env
    entrypoint: docker/entrypoint.sh
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
        - db

volumes:
  postgis-data: