FROM ruby:3.2.0-bullseye
RUN apt-get update &&  apt-get install -y \
      build-essential \
      postgresql-client\
      git-core \
      && apt-get autoremove 


ARG USER_ID=1000
ARG GROUP_ID=1000
ARG PLATFORM=Linux

ENV HOME /home/dockeruser
ENV RAILS_ROOT $HOME/app
RUN mkdir -p $RAILS_ROOT

WORKDIR $RAILS_ROOT
COPY --chown=$USER_ID:$GROUP_ID Gemfile Gemfile.lock ./
RUN gem install bundler 
RUN bundle install --jobs 20 --retry 5

COPY --chown=$USER_ID:$GROUP_ID . ./